import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Guilherme
 *//**
 *
 * @author Guilherme
 *//**
 *
 * @author Guilherme
 *//**
 *
 * @author Guilherme
 *//**
 *
 * @author Guilherme
 *//**
 *
 * @author Guilherme
 *//**
 *
 * @author Guilherme
 *//**
 *
 * @author Guilherme
 */
public class atividade extends javax.swing.JFrame {

    /**
     * Creates new form atividade
     */
    public atividade() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtval1 = new javax.swing.JTextField();
        txtval2 = new javax.swing.JTextField();
        btmSomar = new javax.swing.JButton();
        btmSub = new javax.swing.JButton();
        btmDiv = new javax.swing.JButton();
        btmMult = new javax.swing.JButton();
        txtresultado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Valor1");

        jLabel2.setText("Valor2");

        jLabel3.setText("Resultado");

        txtval2.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        btmSomar.setText("Somar");
        btmSomar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmSomarActionPerformed(evt);
            }
        });

        btmSub.setText("Subtrair");
        btmSub.setActionCommand("Subtrair");
        btmSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmSubActionPerformed(evt);
            }
        });

        btmDiv.setText("Dividir");
        btmDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmDivActionPerformed(evt);
            }
        });

        btmMult.setText("Multiplicar");
        btmMult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmMultActionPerformed(evt);
            }
        });

        txtresultado.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btmSomar)
                        .addGap(18, 18, 18)
                        .addComponent(btmSub)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btmDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btmMult))
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtresultado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                        .addComponent(txtval1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtval2, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jLabel2))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtval1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtval2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btmSomar)
                    .addComponent(btmSub)
                    .addComponent(btmMult)
                    .addComponent(btmDiv))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(txtresultado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btmSomarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmSomarActionPerformed
double val1, val2, result;
val1 = Double.valueOf(txtval1.getText());
val2 = Double.valueOf(txtval2.getText());
result = val1 + val2;
txtresultado.setText(String.valueOf(result));        // TODO add your handling code here:
    }//GEN-LAST:event_btmSomarActionPerformed

    private void btmSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmSubActionPerformed
double val1, val2, result;
val1 = Double.valueOf(txtval1.getText());
val2 = Double.valueOf(txtval2.getText());
result = val1 - val2;
txtresultado.setText(String.valueOf(result));        // TODO add your handling code here:
    }//GEN-LAST:event_btmSubActionPerformed

    private void btmDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmDivActionPerformed
double val1, val2, result;
val1 = Double.valueOf(txtval1.getText());
val2 = Double.valueOf(txtval2.getText());
result = val1 / val2;
if (val2 == 0){
  JOptionPane.showMessageDialog(this, "Não há divisão por 0");

} else txtresultado.setText(String.valueOf(result));
  /*}*/
    
// TODO add your handling code here:
    }//GEN-LAST:event_btmDivActionPerformed

    private void btmMultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmMultActionPerformed
double val1, val2, result;
val1 = Double.valueOf(txtval1.getText());
val2 = Double.valueOf(txtval2.getText());
result = val1 * val2;
        txtresultado.setText(String.valueOf(result));
       // TODO add your handling code here:
    }//GEN-LAST:event_btmMultActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(atividade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(atividade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(atividade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(atividade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new atividade().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btmDiv;
    private javax.swing.JButton btmMult;
    private javax.swing.JButton btmSomar;
    private javax.swing.JButton btmSub;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtresultado;
    private javax.swing.JTextField txtval1;
    private javax.swing.JTextField txtval2;
    // End of variables declaration//GEN-END:variables
}
